### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by rainbowwarmth** [KuroshioDev/koishi-plugin-genshin#1]
求回复
![304d286feb413bb5](https://user-images.githubusercontent.com/94736026/222217792-9188e1fb-4a03-40ca-b223-b9654009c64f.png)
![-10c7f2805edd90ca](https://user-images.githubusercontent.com/94736026/222217815-02b6e18c-e40d-44ea-9ee1-3894e4d2cf5d.jpg)

**Comment by KuroshioDev** [comment]
正在处理

**Comment by KuroshioDev** [comment]
已解决
