### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by FangDoudouY** [KuroshioDev/koishi-plugin-genshin#2]
![image](https://user-images.githubusercontent.com/74800092/222950830-0b8ff082-2a03-4b37-a27c-1b5c047a81ea.png)

**Comment by KuroshioDev** [comment]
升级一下puppeteer

**Comment by KuroshioDev** [comment]
新版本已发布，按最新的安装模式安装，不使用桌面版

**Comment by FangDoudouY** [comment]
谢谢
